name: "PR Title"

on:
    pull_request:
        types:
            - opened
            - edited
            - synchronize

jobs:
    pr_title:
        name: "PR Title"
        runs-on: "self-hosted"
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              with:
                  scopes: |
                      repo
                      server
                      client
                  subjectPattern: ^(?![A-Z]).+$
                  subjectPatternError: |
                      The subject "{subject}" found in the pull request title "{title}"
                      didn't match the configured pattern. Please ensure that the subject
                      doesn't start with an uppercase character.
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
